sudo: required

services:
 - docker

language: rust
rust: nightly

install: cargo build --verbose

before_script:
  - sudo apt-get update

script:
  - cargo test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull oxyl/feeds
  - docker build -t oxyl/feeds .
  - docker push oxyl/feeds