[package]
name = "feeds"
version = "0.1.0"
authors = ["GitStonic <kingstonicthe1@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.89"
dotenv = "0.13.0"
reqwest = "0.9.12"
eventual = "0.1.7"
serde_json = "1.0.39"
serde_derive = "1.0.80"