[package]
name = "feeds"
version = "0.1.0"
authors = ["GitStonic <kingstonicthe1@gmail.com>"]
edition = "2018"

[dependencies]
hyper  = "0.12"
dotenv = "0.13"
redis = "0.10"
tokio = "0.1"
zmq = "0.9"

[dependencies.serde]
version = "1.0"
features = ["derive"]