[package]
name = "feeds"
version = "0.1.0"
authors = ["GitStonic <kingstonicthe1@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.80"
reqwest = "0.9.4"
futures = "0.1.25"
tokio-timer = "0.2.7"
serde_json = "1.0.32"
serde_derive = "1.0.80"